spec:
  template:
    spec:
      containers:
        - env:
          - name: spring_kafka_consumer_bootstrap_servers
            value: kafka:9092
          - name: spring_kafka_producer_bootstrap_servers
            value: kafka:9092